@local= http://localhost:3000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdyYmhlQGdyZ3IuY29tIiwiX2lkIjoiNjQwYmZlMmMwNjU5ZjVhMjdiYzk0MWQ0IiwidmlwIjp0cnVlLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNjc4NjI1MTI2fQ.jSOdIZA3BJgJnJLcMrH7oONHS50Z1V0YKl3W9t6topU
POST {{local}}/admin
Content-Type: application/json

{"email":"4@gmail.com", "password":"111111"}



###
GET {{local}}/users/get-favorites/640df4915e4e3e14436d177a
Content-Type: application/json

###
GET {{local}}/users/64354a149688ac7226af1c8b
Content-Type: application/json
###
GET {{local}}/users/get-blocked/6431e8e78a8c0d185d095982
Content-Type: application/json

###
POST {{local}}/me/remove-favorites/640deb6e81b08c9a1ad186e2
Content-Type: application/json
x-auth-token:{{token}}

{ "email": "111@g.com" }

###

PUT {{local}}/admin/change-vip/6419a5bc57fefdeecc496e94?email=wfee@g.com`
Content-Type: application/json
x-auth-token:{{token}}


{"isVip":false}
###

POST {{local}}/me/favorites/640deb6e81b08c9a1ad186e2
x-auth-token:{{token}}
Content-Type: application/json

{"email":"111@g.com"}

###

POST {{local}}/me/remove-block/6431d579de8435f6844aa320
x-auth-token:{{token}}
Content-Type: application/json

{"email":"444@g.com"}
###
POST {{local}}/me/block/6428969115697704fa8efc33
x-auth-token:{{token}}
Content-Type: application/json

{"email":"rhehhbeb@g.com"}

###

POST {{local}}/users/vip
Content-Type: application/json

{"email":"22@g.com","cardNumber":"ffffgff"}

###

GET {{local}}/admin/vip-req
Content-Type: application/json

###

DELETE {{local}}/admin/delete-vip-req/6419a5bc57fefdeecc496e94
x-auth-token:{{token}}
Content-Type: application/json

{"email":"eee@g.com"}

